(() => {
const $=id=>document.getElementById(id), n=id=>{const v=Number($(id)?.value);return Number.isFinite(v)?v:null}, out=(v,l)=>{const e=$('result');if(e)e.innerHTML=`<strong>${v}</strong><span>${l}</span>`}, bad=m=>out('⚠️',m);
const calc={
 tip:()=>{let b=n('bill'),p=n('people'),t=n('tip');if(b==null||p==null||t==null||b<0||p<1)return bad('请输入有效的账单金额、人数和小费比例');let x=b*t/100;out('$'+(x/p+x*0).toFixed(2),'小费 $'+x.toFixed(2)+' · 总额 $'+(b+x).toFixed(2)+' · 每人 $'+((b+x)/p).toFixed(2))},
 salary:()=>{let a=n('annual');if(a==null||a<0)return bad('请输入有效年薪');out('$'+(a/12).toFixed(2),'月薪税前 · 周薪约 $'+(a/52).toFixed(2))},
 hourly:()=>{let h=n('hourly'),w=n('hours'),y=n('weeks');if(h==null||w==null||y==null||h<0||w<0||w>168||y<1||y>52)return bad('请检查时薪、每周工时和工作周数');let a=h*w*y;out('$'+a.toFixed(2),'估算年薪税前 · 月薪约 $'+(a/12).toFixed(2))},
 split:()=>{let b=n('bill'),p=n('people'),t=n('tip');if(b==null||p==null||t==null||b<0||p<1||t<0||t>100)return bad('请输入有效数值');let total=b*(1+t/100);out('$'+(total/p).toFixed(2),'每人应付 · 小费 $'+(b*t/100).toFixed(2)+' · 总计 $'+total.toFixed(2))},
 tax:()=>{let p=n('price'),t=n('tax');if(p==null||t==null||p<0||t<0||t>100)return bad('请输入有效价格和税率');out('$'+(p*(1+t/100)).toFixed(2),'含税价格 · 税额 $'+(p*t/100).toFixed(2))},
 discount:()=>{let p=n('price'),d=n('discount');if(p==null||d==null||p<0||d<0||d>100)return bad('请输入有效原价和折扣');out('$'+(p*(1-d/100)).toFixed(2),'折后价格 · 节省 $'+(p*d/100).toFixed(2))},
 currency:()=>{let a=n('amount'),r=n('rate'),dir=$('direction').value;if(a==null||r==null||a<0||r<=0)return bad('请输入有效金额和汇率');let v=dir==='USD-CNY'?a*r:a/r;out((dir==='USD-CNY'?'¥':'$')+v.toFixed(2),'换算结果 · 1 USD = '+r.toFixed(4)+' CNY')},
 temp:()=>{let v=n('value'),d=$('direction').value;if(v==null)return bad('请输入温度');let r=d==='F-C'?(v-32)*5/9:v*9/5+32;out(r.toFixed(2)+'°','换算结果')},
 weight:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效重量');let r={lbkg:v*.45359237,kglb:v/.45359237,ozg:v*28.349523125,gzo:v/28.349523125}[d];out(r.toFixed(2),'换算结果')},
 length:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效长度');let r={incm:v*2.54,cmin:v/2.54,ftm:v*.3048,mft:v/.3048}[d];out(r.toFixed(2),'换算结果')},
 distance:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效距离');let r=d==='mi-km'?v*1.609344:v/1.609344;out(r.toFixed(2),'换算结果')},
 area:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效面积');let r={ftm:v*.09290304,mft:v/.09290304,acrem:v*4046.8564224,macre:v/4046.8564224}[d];out(r.toFixed(2),'换算结果')},
 volume:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效容量');let r={gl:v*3.785411784,lg:v/3.785411784,ql:v*.946352946,lq:v/.946352946}[d];out(r.toFixed(2),'换算结果')},
 mpg:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<=0)return bad('请输入大于 0 的数值');let r=d==='mpg-l'?235.214583/v:v?235.214583/v:0;out(r.toFixed(2),'换算结果')},
 gas:()=>{let m=n('miles'),g=n('mpg'),p=n('price');if(m==null||g==null||p==null||m<0||g<=0||p<0)return bad('请输入有效里程、MPG 和油价');let gal=m/g;out('$'+(gal*p).toFixed(2),'预计油费 · 约 '+gal.toFixed(2)+' gallon')},
 car:()=>loan('price','down','rate','months','汽车月供',12), mortgage:()=>loan('price','down','rate','years','房贷月供',1),
 time:()=>{let v=$('localtime').value;if(!v)return bad('请选择美国当地日期和时间');let d=new Date(v);let zone=$('zone').value;let zones={ET:'America/New_York',CT:'America/Chicago',MT:'America/Denver',PT:'America/Los_Angeles'};let parts=new Intl.DateTimeFormat('zh-CN',{timeZone:zones[zone],year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(d);let get=x=>parts.find(p=>p.type===x)?.value;let date=get('year')+'-'+get('month')+'-'+get('day')+' '+get('hour')+':'+get('minute');let cn=new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(d);out(date,'美国当地时间 · 中国北京时间 '+cn)},
 age:()=>{let s=$('birth').value;if(!s)return bad('请选择出生日期');let b=new Date(s+'T00:00:00'),now=new Date();if(b>now)return bad('出生日期不能晚于今天');let a=now.getFullYear()-b.getFullYear();if(now.getMonth()<b.getMonth()||(now.getMonth()===b.getMonth()&&now.getDate()<b.getDate()))a--;out(a+' 岁','当前年龄')},
 date:()=>{let a=$('start').value,b=$('end').value;if(!a||!b)return bad('请选择两个日期');out(Math.round(Math.abs(new Date(b)-new Date(a))/86400000)+' 天','两个日期相差')},
 shoe:()=>{let v=n('value'),d=$('direction').value;if(v==null)return bad('请输入鞋码');let r=v-33.5;if(d==='us-cn')r=v+33.5;out(r.toFixed(1),'参考鞋码 · 品牌尺码表优先')},
 mattress:()=>{let x={Twin:['38 × 75 in','96.5 × 190.5 cm'],TwinXL:['38 × 80 in','96.5 × 203.2 cm'],Full:['54 × 75 in','137.2 × 190.5 cm'],Queen:['60 × 80 in','152.4 × 203.2 cm'],King:['76 × 80 in','193 × 203.2 cm'],CalKing:['72 × 84 in','182.9 × 213.4 cm']}[$('size').value];out(x[0],x[1])},
 psi:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效压力');out((d==='psi-bar'?v*.0689475729:v/.0689475729).toFixed(2),'换算结果')},
 hp:()=>{let v=n('value'),d=$('direction').value;if(v==null||v<0)return bad('请输入有效功率');out((d==='hp-kw'?v*.745699872:v/.745699872).toFixed(2),'换算结果')}
};
function loan(p,d,r,nm,label,unit){let price=n(p),down=n(d),rate=n(r),term=n(nm);if(price==null||down==null||rate==null||term==null||price<0||down<0||down>price||rate<0||rate>100||term<1)return bad('请检查输入数值');let principal=price-down,monthly=rate?(()=>{let rr=rate/1200;return principal*rr*Math.pow(1+rr,term*unit)/(Math.pow(1+rr,term*unit)-1)})():principal/(term*unit);out('$'+monthly.toFixed(2),'预计每月 · 本金 $'+principal.toFixed(2))}
const key=document.body.dataset.tool;if(calc[key]){const b=$('calculate');b?.addEventListener('click',calc[key]);if(key==='mattress')$('size')?.addEventListener('change',calc[key]);}
})();