const tools=[{id:'tip-calculator',cat:'钱 & 工资',icon:'💵',name:'小费计算器',desc:'餐厅、外卖、理发等快速计算小费',popular:1},{id:'salary-calculator',cat:'钱 & 工资',icon:'💰',name:'税前工资估算',desc:'年薪、月薪、周薪快速换算',popular:1},{id:'hourly-to-salary',cat:'钱 & 工资',icon:'🧮',name:'时薪转年薪',desc:'输入时薪和工作时间估算年收入',popular:1},{id:'split-bill',cat:'钱 & 工资',icon:'🧾',name:'AA 分账计算器',desc:'多人吃饭快速平均分账',popular:1},{id:'sales-tax',cat:'钱 & 工资',icon:'🏷️',name:'Sales Tax 计算器',desc:'商品价格加销售税计算最终付款',popular:1},{id:'discount',cat:'购物',icon:'🛍️',name:'折扣计算器',desc:'计算打折后的价格和省下多少钱',popular:1},{id:'currency',cat:'钱 & 工资',icon:'💱',name:'美元人民币换算',desc:'美元与人民币快速换算',popular:1},{id:'temp',cat:'单位换算',icon:'🌡️',name:'华氏度 ↔ 摄氏度',desc:'美国天气和生活温度快速换算',popular:1},{id:'weight',cat:'单位换算',icon:'⚖️',name:'磅 ↔ 公斤',desc:'lb、kg、oz 日常重量换算',popular:1},{id:'length',cat:'单位换算',icon:'📏',name:'英寸 ↔ 厘米',desc:'inch、cm、feet 快速换算'},{id:'distance',cat:'单位换算',icon:'🚗',name:'英里 ↔ 公里',desc:'Miles 与 KM 快速换算',popular:1},{id:'area',cat:'单位换算',icon:'🏠',name:'平方英尺 ↔ 平方米',desc:'美国房屋面积快速换算',popular:1},{id:'volume',cat:'单位换算',icon:'🥛',name:'加仑 ↔ 升',desc:'Gallon、Liter、Quart 换算'},{id:'mpg',cat:'汽车',icon:'⛽',name:'MPG ↔ L/100km',desc:'美国汽车油耗换算',popular:1},{id:'gas-cost',cat:'汽车',icon:'⛽',name:'加油成本计算器',desc:'估算一次开车需要多少油钱'},{id:'car-payment',cat:'汽车',icon:'🚙',name:'汽车月供计算器',desc:'根据车价、利率和期限计算月供',popular:1},{id:'mortgage',cat:'房屋',icon:'🏡',name:'房贷月供计算器',desc:'估算本金、利息和每月付款',popular:1},{id:'china-us-time',cat:'时间日期',icon:'🕐',name:'中美时间转换',desc:'美国时间与中国时间快速转换',popular:1},{id:'age',cat:'时间日期',icon:'🎂',name:'年龄计算器',desc:'输入生日计算准确年龄'},{id:'date-diff',cat:'时间日期',icon:'📅',name:'日期差计算器',desc:'计算两个日期相差多少天'},{id:'shoe-size',cat:'尺码',icon:'👟',name:'中美鞋码转换',desc:'中国、US、EU 鞋码参考'},{id:'mattress',cat:'尺码',icon:'🛏️',name:'美国床垫尺寸',desc:'Twin、Full、Queen、King 尺寸查询'},{id:'psi',cat:'汽车 / 技术',icon:'🔧',name:'PSI ↔ Bar',desc:'轮胎气压和工业压力换算'},{id:'hp-kw',cat:'汽车 / 技术',icon:'⚡',name:'HP ↔ kW',desc:'马力与千瓦快速换算'}];
const $=id=>document.getElementById(id); const fmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:2});
function card(t,mini=false){return `<a class="${mini?'mini-card':'tool-card'}" href="tools/${t.id}.html"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p></a>`}
function renderHome(){const p=$('popular-grid'),c=$('category-list');if(!p||!c)return;p.innerHTML=tools.filter(t=>t.popular).map(t=>card(t)).join('');const cats={};tools.forEach(t=>(cats[t.cat]??=[]).push(t));const ids={'钱 & 工资':'money','购物':'shopping','汽车':'auto','房屋':'home','单位换算':'units','时间日期':'time','尺码':'size','汽车 / 技术':'tech'};c.innerHTML=Object.entries(cats).map(([cat,arr])=>`<div class="category" id="${ids[cat]||'other'}"><h3>${cat}</h3><div class="category-grid">${arr.map(t=>card(t,true)).join('')}</div></div>`).join('');$('tool-search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#popular-grid .tool-card,#category-list .mini-card').forEach(el=>el.style.display=!q||el.textContent.toLowerCase().includes(q)?'block':'none')})}
function input(id,label,value='',type='number',step='any'){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" step="${step}"></div>`} function select(id,label,opts){return `<div class="field"><label for="${id}">${label}</label><select id="${id}">${opts.map(o=>`<option>${o}</option>`).join('')}</select></div>`} function result(v,l){return `<div class="result"><div class="big">${v}</div><div class="label">${l}</div></div>`}
function shell(t,body,note=''){return `<header class="site-header"><a class="brand" href="/"><span class="brand-mark">T</span>ToolKu</a><nav><a href="/">首页</a><a href="/#tool-nav">工具导航</a><a href="/#categories">全部工具</a><a href="https://openaa.com" target="_blank" rel="noopener">OpenAA</a></nav></header><main class="tool-shell"><section class="tool-page"><h1>${t.icon} ${t.name}</h1><p class="subtitle">${t.desc}</p>${body}${note?`<div class="note">${note}</div>`:''}<div class="tool-nav"><a href="/">← 返回 ToolKu</a><a href="/#tool-nav">工具导航</a></div></section></main><footer>ToolKu.com · 美国华人生活工具箱<br><small>计算结果仅供参考；汇率、税率、贷款等会随实际情况变化。</small></footer>`}
function calculator(id){const t=tools.find(x=>x.id===id)||tools[0];let b='',fn=()=>{} ,n='';
const button=`<div class="buttons"><button type="button" class="btn primary" id="calc-btn">计算</button></div><div id="out"></div>`;
if(id==='tip-calculator'){b=input('bill','账单金额 ($)',100)+select('tip','小费比例',['15%','18%','20%','25%'])+input('people','人数',1,'number','1')+button;fn=()=>{let bill=+$('bill').value||0,p=parseFloat($('tip').value)/100,people=Math.max(1,+$('people').value||1),tip=bill*p,total=bill+tip;$('out').innerHTML=result('$'+fmt(tip),'小费 · 每人 $'+fmt(total/people)+' · 含小费总额 $'+fmt(total))}}
else if(id==='salary-calculator'){b=input('a','年薪 ($)',60000)+button;fn=()=>{let a=+$('a').value||0;$('out').innerHTML=result('$'+fmt(a/12),'月薪税前 · 周薪约 $'+fmt(a/52))}}
else if(id==='hourly-to-salary'){b=input('h','时薪 ($)',25)+input('w','每周工作小时',40)+input('y','每年工作周数',52)+button;fn=()=>{let h=+$('h').value||0,w=+$('w').value||0,y=+$('y').value||52,a=h*w*y;$('out').innerHTML=result('$'+fmt(a),'估算年薪（税前） · 月薪约 $'+fmt(a/12))}}
else if(id==='split-bill'){b=input('b','总账单 ($)',200)+input('p','人数',4,'number','1')+input('t','小费比例 (%)',20)+button;fn=()=>{let bill=+$('b').value||0,p=Math.max(1,+$('p').value||1),t=(+$('t').value||0)/100,total=bill*(1+t);$('out').innerHTML=result('$'+fmt(total/p),'每人应付 · 小费 $'+fmt(bill*t)+' · 总计 $'+fmt(total))}}
else if(id==='sales-tax'){b=input('p','商品价格 ($)',100)+input('t','销售税率 (%)',8.875)+button;fn=()=>{let p=+$('p').value||0,t=(+$('t').value||0)/100;$('out').innerHTML=result('$'+fmt(p*(1+t)),'最终价格 · 税额 $'+fmt(p*t))};n='税率按你输入的数值计算；不同州、县、市及商品类别可能不同。'}
else if(id==='discount'){b=input('p','原价 ($)',100)+input('o','折扣 (%)',20)+button;fn=()=>{let p=+$('p').value||0,o=(+$('o').value||0)/100;$('out').innerHTML=result('$'+fmt(p*(1-o)),'折后价格 · 节省 $'+fmt(p*o))}}
else if(id==='currency'){b=input('a','金额',100)+select('d','换算方向',['USD → CNY','CNY → USD'])+input('r','汇率（1 USD = CNY）',7.2)+button;fn=()=>{let a=+$('a').value||0,r=+$('r').value||7.2,c=$('d').value==='USD → CNY',v=c?a*r:a/r;$('out').innerHTML=result((c?'¥':'$')+fmt(v),'换算结果 · 1 USD = '+fmt(r)+' CNY')};n='汇率可自行修改，建议参考银行或实时汇率。'}
else if(id==='temp'){b=input('v','温度',32)+select('d','换算方向',['°F → °C','°C → °F'])+button;fn=()=>{let v=+$('v').value||0,r=$('d').value==='°F → °C'?(v-32)*5/9:v*9/5+32;$('out').innerHTML=result(fmt(r)+'°','换算结果')}}
else if(id==='weight'){b=input('v','重量',1)+select('d','换算方向',['lb → kg','kg → lb','oz → g','g → oz'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='lb → kg'?v*.45359237:d==='kg → lb'?v/.45359237:d==='oz → g'?v*28.349523125:v/28.349523125;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='length'){b=input('v','长度',1)+select('d','换算方向',['inch → cm','cm → inch','feet → meter','meter → feet'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='inch → cm'?v*2.54:d==='cm → inch'?v/2.54:d==='feet → meter'?v*.3048:v/.3048;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='distance'){b=input('v','距离',1)+select('d','换算方向',['Miles → KM','KM → Miles'])+button;fn=()=>{let v=+$('v').value||0,r=$('d').value==='Miles → KM'?v*1.609344:v/1.609344;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='area'){b=input('v','面积',1000)+select('d','换算方向',['sq ft → ㎡','㎡ → sq ft','acre → ㎡','㎡ → acre'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='sq ft → ㎡'?v*.09290304:d==='㎡ → sq ft'?v/.09290304:d==='acre → ㎡'?v*4046.8564224:v/4046.8564224;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='volume'){b=input('v','容量',1)+select('d','换算方向',['Gallon → Liter','Liter → Gallon','Quart → Liter','Liter → Quart'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='Gallon → Liter'?v*3.785411784:d==='Liter → Gallon'?v/3.785411784:d==='Quart → Liter'?v*.946352946:v/.946352946;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='mpg'){b=input('v','数值',25)+select('d','换算方向',['MPG → L/100km','L/100km → MPG'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=235.214583/v;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='gas-cost'){b=input('m','行驶里程 (miles)',100)+input('g','车辆 MPG',25)+input('p','汽油价格 ($/gallon)',3.5)+button;fn=()=>{let m=+$('m').value||0,g=+$('g').value||1,p=+$('p').value||0,gallons=m/g;$('out').innerHTML=result('$'+fmt(gallons*p),'预计油费 · 用油 '+fmt(gallons)+' gallon')}}
else if(id==='car-payment'){b=input('p','车价 ($)',30000)+input('d','首付 ($)',5000)+input('r','年利率 (%)',6.5)+input('n','贷款期限（月）',60,'number','1')+button;fn=()=>{let p=Math.max(0,(+$('p').value||0)-($('d').value||0)),r=(+$('r').value||0)/1200,n=Math.max(1,+$('n').value||60),m=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;$('out').innerHTML=result('$'+fmt(m),'预计月供 · 贷款本金 $'+fmt(p)+' · 总还款约 $'+fmt(m*n))};n='未包含销售税、牌照、Dealer fee、保险等实际购车成本。'}
else if(id==='mortgage'){b=input('p','房价 ($)',500000)+input('d','首付 ($)',100000)+input('r','年利率 (%)',6.5)+input('n','贷款年限',30,'number','1')+button;fn=()=>{let p=Math.max(0,(+$('p').value||0)-($('d').value||0)),r=(+$('r').value||0)/1200,n=Math.max(1,(+$('n').value||30)*12),m=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;$('out').innerHTML=result('$'+fmt(m),'每月本金+利息 · 贷款本金 $'+fmt(p)+' · 总还款约 $'+fmt(m*n))};n='这里只计算本金和利息（P&I），未包含房产税、房屋保险、HOA 等费用。'}
else if(id==='china-us-time'){b=select('z','美国时区',['纽约 Eastern Time','芝加哥 Central Time','丹佛 Mountain Time','洛杉矶 Pacific Time'])+input('t','美国当地时间','','datetime-local')+button;fn=()=>{let v=$('t').value;if(!v){$('out').innerHTML=result('请选择时间','请输入美国当地日期和时间');return}let d=new Date(v),off={'纽约 Eastern Time':-4,'芝加哥 Central Time':-5,'丹佛 Mountain Time':-6,'洛杉矶 Pacific Time':-7}[$('z').value],cn=new Date(d.getTime()-off*3600000+8*3600000);$('out').innerHTML=result(cn.toISOString().slice(0,16).replace('T',' '),'中国北京时间（夏令时近似）')}};n='美国各时区存在夏令时变化，结果适合作为日常快速换算参考。'}
else if(id==='age'){b=input('b','出生日期','','date')+button;fn=()=>{let v=$('b').value;if(!v){$('out').innerHTML=result('请选择日期','请输入出生日期');return}let b=new Date(v+'T00:00:00'),now=new Date(),a=now.getFullYear()-b.getFullYear();if(now.getMonth()<b.getMonth()||(now.getMonth()===b.getMonth()&&now.getDate()<b.getDate()))a--;$('out').innerHTML=result(a+' 岁','当前年龄')}}
else if(id==='date-diff'){b=input('a','开始日期','','date')+input('b','结束日期','','date')+button;fn=()=>{let a=new Date($('a').value+'T00:00:00'),b=new Date($('b').value+'T00:00:00');if(isNaN(a)||isNaN(b)){ $('out').innerHTML=result('请选择日期','请输入开始和结束日期');return }$('out').innerHTML=result(fmt(Math.round(Math.abs(b-a)/86400000))+' 天','两个日期相差')}}
else if(id==='shoe-size'){b=select('d','换算方向',['中国男鞋码 → US 男鞋','US 男鞋 → 中国码','中国女鞋码 → US 女鞋','US 女鞋 → 中国女鞋'])+input('v','鞋码',42)+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='中国男鞋码 → US 男鞋'?v-18:d==='US 男鞋 → 中国码'?v+18:d==='中国女鞋码 → US 女鞋'?v-18.5:v+18.5;$('out').innerHTML=result(fmt(r),'参考鞋码')}};n='不同品牌、鞋型和地区标准可能有差异，购买前建议查看品牌官方尺码表。'}
else if(id==='mattress'){b=select('d','床垫尺寸',['Twin','Twin XL','Full / Double','Queen','King','California King'])+`<div id="out" class="result"><div class="big">38 × 75 in</div><div class="label">约 96.5 × 190.5 cm</div></div>`;fn=()=>{const x={Twin:['38 × 75 in','约 96.5 × 190.5 cm'],'Twin XL':['38 × 80 in','约 96.5 × 203.2 cm'],'Full / Double':['54 × 75 in','约 137.2 × 190.5 cm'],Queen:['60 × 80 in','约 152.4 × 203.2 cm'],King:['76 × 80 in','约 193 × 203.2 cm'],'California King':['72 × 84 in','约 182.9 × 213.4 cm']}[$('d').value];$('out').querySelector('.big').textContent=x[0];$('out').querySelector('.label').textContent=x[1]};n='美国常见床垫标准尺寸参考，实际产品尺寸可能因品牌略有差异。'}
else if(id==='psi'){b=input('v','压力',35)+select('d','换算方向',['PSI → Bar','Bar → PSI'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='PSI → Bar'?v*.0689475729:v/.0689475729;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='hp-kw'){b=input('v','功率',100)+select('d','换算方向',['HP → kW','kW → HP'])+button;fn=()=>{let v=+$('v').value||0,d=$('d').value,r=d==='HP → kW'?v*.745699872:v/.745699872;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
return {html:shell(t,b,n),fn};}
function renderTool(){const m=location.pathname.match(/\/tools\/([^/]+)\.html$/);if(!m)return;const x=calculator(m[1]);document.body.innerHTML=x.html;const btn=$('calc-btn');if(btn)btn.addEventListener('click',x.fn)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderHome();renderTool()});else{renderHome();renderTool()}