const tools=[{id:'tip-calculator',cat:'钱 & 工资',icon:'💵',name:'小费计算器',desc:'餐厅、外卖、理发等快速计算小费',popular:1},{id:'salary-calculator',cat:'钱 & 工资',icon:'💰',name:'税前工资估算',desc:'年薪、月薪、周薪快速换算',popular:1},{id:'hourly-to-salary',cat:'钱 & 工资',icon:'🧮',name:'时薪转年薪',desc:'输入时薪和工作时间估算年收入',popular:1},{id:'split-bill',cat:'钱 & 工资',icon:'🧾',name:'AA 分账计算器',desc:'多人吃饭快速平均分账',popular:1},{id:'sales-tax',cat:'钱 & 工资',icon:'🏷️',name:'Sales Tax 计算器',desc:'商品价格加销售税计算最终付款',popular:1},{id:'discount',cat:'购物',icon:'🛍️',name:'折扣计算器',desc:'计算打折后的价格和省下多少钱',popular:1},{id:'currency',cat:'钱 & 工资',icon:'💱',name:'美元人民币换算',desc:'美元与人民币快速换算',popular:1},{id:'temp',cat:'单位换算',icon:'🌡️',name:'华氏度 ↔ 摄氏度',desc:'美国天气和生活温度快速换算',popular:1},{id:'weight',cat:'单位换算',icon:'⚖️',name:'磅 ↔ 公斤',desc:'lb、kg、oz 日常重量换算',popular:1},{id:'length',cat:'单位换算',icon:'📏',name:'英寸 ↔ 厘米',desc:'inch、cm、feet 快速换算'},{id:'distance',cat:'单位换算',icon:'🚗',name:'英里 ↔ 公里',desc:'Miles 与 KM 快速换算',popular:1},{id:'area',cat:'单位换算',icon:'🏠',name:'平方英尺 ↔ 平方米',desc:'美国房屋面积快速换算',popular:1},{id:'volume',cat:'单位换算',icon:'🥛',name:'加仑 ↔ 升',desc:'Gallon、Liter、Quart 换算'},{id:'mpg',cat:'汽车',icon:'⛽',name:'MPG ↔ L/100km',desc:'美国汽车油耗换算',popular:1},{id:'gas-cost',cat:'汽车',icon:'⛽',name:'加油成本计算器',desc:'估算一次开车需要多少油钱'},{id:'car-payment',cat:'汽车',icon:'🚙',name:'汽车月供计算器',desc:'根据车价、利率和期限计算月供',popular:1},{id:'mortgage',cat:'房屋',icon:'🏡',name:'房贷月供计算器',desc:'估算本金、利息和每月付款',popular:1},{id:'china-us-time',cat:'时间日期',icon:'🕐',name:'中美时间转换',desc:'美国时间与中国时间快速转换',popular:1},{id:'age',cat:'时间日期',icon:'🎂',name:'年龄计算器',desc:'输入生日计算准确年龄'},{id:'date-diff',cat:'时间日期',icon:'📅',name:'日期差计算器',desc:'计算两个日期相差多少天'},{id:'shoe-size',cat:'尺码',icon:'👟',name:'中美鞋码转换',desc:'中国、US、EU 鞋码参考'},{id:'mattress',cat:'尺码',icon:'🛏️',name:'美国床垫尺寸',desc:'Twin、Full、Queen、King 尺寸查询'},{id:'psi',cat:'汽车 / 技术',icon:'🔧',name:'PSI ↔ Bar',desc:'轮胎气压和工业压力换算'},{id:'hp-kw',cat:'汽车 / 技术',icon:'⚡',name:'HP ↔ kW',desc:'马力与千瓦快速换算'}];
const $=id=>document.getElementById(id);const fmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:2});
function card(t,mini=false){return `<a class="${mini?'mini-card':'tool-card'}" href="tools/${t.id}.html"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p></a>`}
function renderHome(){const p=$('popular-grid'),c=$('category-list');if(!p||!c)return;p.innerHTML=tools.filter(t=>t.popular).map(t=>card(t)).join('');const cats={};tools.forEach(t=>(cats[t.cat]??=[]).push(t));const ids={'钱 & 工资':'money','购物':'shopping','汽车':'auto','房屋':'home','单位换算':'units','时间日期':'time','尺码':'size','汽车 / 技术':'tech'};c.innerHTML=Object.entries(cats).map(([cat,arr])=>`<div class="category" id="${ids[cat]||'other'}"><h3>${cat}</h3><div class="category-grid">${arr.map(t=>card(t,true)).join('')}</div></div>`).join('');$('tool-search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#popular-grid .tool-card,#category-list .mini-card').forEach(el=>el.style.display=!q||el.textContent.toLowerCase().includes(q)?'block':'none')})}
function input(id,label,value='',type='number',step='any'){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" step="${step}" inputmode="decimal"></div>`}function select(id,label,opts){return `<div class="field"><label for="${id}">${label}</label><select id="${id}">${opts.map(o=>`<option>${o}</option>`).join('')}</select></div>`}function result(v,l){return `<div class="result"><div class="big">${v}</div><div class="label">${l}</div></div>`}function bad(msg='请输入有效数值'){$('out').innerHTML=result('⚠️',msg)}function num(id,min=null,max=null){const v=Number($(id)?.value);if(!Number.isFinite(v))return null;if(min!==null&&v<min)return null;if(max!==null&&v>max)return null;return v}
function shell(t,body,note=''){return `<header class="site-header"><a class="brand" href="/"><span class="brand-mark">T</span>ToolKu</a><nav><a href="/">首页</a><a href="/#tool-nav">工具导航</a><a href="/#categories">全部工具</a><a href="https://openaa.com" target="_blank" rel="noopener">OpenAA</a></nav></header><main class="tool-shell"><section class="tool-page"><h1>${t.icon} ${t.name}</h1><p class="subtitle">${t.desc}</p>${body}${note?`<div class="note">${note}</div>`:''}<div class="tool-nav"><a href="/">← 返回 ToolKu</a><a href="/#tool-nav">工具导航</a><a href="/#categories">全部工具</a></div></section></main><footer>ToolKu.com · 美国华人生活工具箱<br><small>计算结果仅供参考；税务、汇率、贷款、尺码等请以实际情况为准。</small></footer>`}
function calculator(id){const t=tools.find(x=>x.id===id);if(!t)return null;let b='',fn=()=>{},n='';const button=`<div class="buttons"><button type="button" class="btn primary" id="calc-btn">计算</button></div><div id="out"></div>`;
if(id==='tip-calculator'){b=input('bill','账单金额 ($)',100)+select('tip','小费比例',['15%','18%','20%','25%'])+input('people','人数',1,'number','1')+button;fn=()=>{let bill=num('bill',0),people=num('people',1);if(bill===null||people===null)return bad('请输入有效的账单金额和人数');let p=parseFloat($('tip').value)/100,tip=bill*p,total=bill+tip;$('out').innerHTML=result('$'+fmt(tip),'小费 · 每人 $'+fmt(total/people)+' · 含小费总额 $'+fmt(total))}}
else if(id==='salary-calculator'){b=input('a','年薪 ($)',60000)+button;fn=()=>{let a=num('a',0);if(a===null)return bad('请输入有效的年薪');$('out').innerHTML=result('$'+fmt(a/12),'月薪税前 · 周薪约 $'+fmt(a/52))}}
else if(id==='hourly-to-salary'){b=input('h','时薪 ($)',25)+input('w','每周工作小时',40)+input('y','每年工作周数',52)+button;fn=()=>{let h=num('h',0),w=num('w',0,168),y=num('y',1,52);if(h===null||w===null||y===null)return bad('请输入有效的时薪、工时和工作周数');let a=h*w*y;$('out').innerHTML=result('$'+fmt(a),'估算年薪（税前） · 月薪约 $'+fmt(a/12))}}
else if(id==='split-bill'){b=input('b','总账单 ($)',200)+input('p','人数',4,'number','1')+input('t','小费比例 (%)',20)+button;fn=()=>{let bill=num('b',0),p=num('p',1),t=num('t',0,100);if(bill===null||p===null||t===null)return bad('请输入有效的账单、人数和小费比例');let total=bill*(1+t/100);$('out').innerHTML=result('$'+fmt(total/p),'每人应付 · 小费 $'+fmt(bill*t/100)+' · 总计 $'+fmt(total))}}
else if(id==='sales-tax'){b=input('p','商品价格 ($)',100)+input('t','销售税率 (%)',8.875)+button;fn=()=>{let p=num('p',0),t=num('t',0,100);if(p===null||t===null)return bad('请输入有效的价格和税率');$('out').innerHTML=result('$'+fmt(p*(1+t/100)),'最终价格 · 税额 $'+fmt(p*t/100))};n='税率按你输入的数值计算；不同州、县、市及商品类别可能不同。'}
else if(id==='discount'){b=input('p','原价 ($)',100)+input('o','折扣 (%)',20)+button;fn=()=>{let p=num('p',0),o=num('o',0,100);if(p===null||o===null)return bad('请输入有效的原价和折扣');$('out').innerHTML=result('$'+fmt(p*(1-o/100)),'折后价格 · 节省 $'+fmt(p*o/100))}}
else if(id==='currency'){b=input('a','金额',100)+select('d','换算方向',['USD → CNY','CNY → USD'])+input('r','汇率（1 USD = CNY）',7.2)+button;fn=()=>{let a=num('a',0),r=num('r',0.000001);if(a===null||r===null)return bad('请输入有效金额和汇率');let c=$('d').value==='USD → CNY',v=c?a*r:a/r;$('out').innerHTML=result((c?'¥':'$')+fmt(v),'换算结果 · 1 USD = '+fmt(r)+' CNY')};n='汇率可自行修改，建议参考银行或实时汇率。'}
else if(id==='temp'){b=input('v','温度',32)+select('d','换算方向',['°F → °C','°C → °F'])+button;fn=()=>{let v=num('v');if(v===null)return bad();let r=$('d').value==='°F → °C'?(v-32)*5/9:v*9/5+32;$('out').innerHTML=result(fmt(r)+'°','换算结果')}}
else if(id==='weight'){b=input('v','重量',1)+select('d','换算方向',['lb → kg','kg → lb','oz → g','g → oz'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='lb → kg'?v*.45359237:d==='kg → lb'?v/.45359237:d==='oz → g'?v*28.349523125:v/28.349523125;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='length'){b=input('v','长度',1)+select('d','换算方向',['inch → cm','cm → inch','feet → meter','meter → feet'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='inch → cm'?v*2.54:d==='cm → inch'?v/2.54:d==='feet → meter'?v*.3048:v/.3048;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='distance'){b=input('v','距离',1)+select('d','换算方向',['Miles → KM','KM → Miles'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let r=$('d').value==='Miles → KM'?v*1.609344:v/1.609344;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='area'){b=input('v','面积',1000)+select('d','换算方向',['sq ft → ㎡','㎡ → sq ft','acre → ㎡','㎡ → acre'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='sq ft → ㎡'?v*.09290304:d==='㎡ → sq ft'?v/.09290304:d==='acre → ㎡'?v*4046.8564224:v/4046.8564224;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='volume'){b=input('v','容量',1)+select('d','换算方向',['Gallon → Liter','Liter → Gallon','Quart → Liter','Liter → Quart'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='Gallon → Liter'?v*3.785411784:d==='Liter → Gallon'?v/3.785411784:d==='Quart → Liter'?v*.946352946:v/.946352946;$('out').innerHTML=result(fmt(r),'换算结果')}}
else if(id==='mpg'){b=input('v','数值',25)+select('d','换算方向',['MPG → L/100km','L/100km → MPG'])+button;fn=()=>{let v=num('v',0.000001);if(v===null)return bad('请输入大于 0 的油耗数值');let r=235.214583/v;$('out').innerHTML=result(fmt(r),$('d').value.split(' → ')[1])}}
else if(id==='gas-cost'){b=input('m','行驶里程 (miles)',100)+input('g','车辆 MPG',25)+input('p','汽油价格 ($/gallon)',3.5)+button;fn=()=>{let m=num('m',0),g=num('g',0.000001),p=num('p',0);if(m===null||g===null||p===null)return bad('请输入有效的里程、MPG 和油价');let gallons=m/g;$('out').innerHTML=result('$'+fmt(gallons*p),'预计油费 · 用油 '+fmt(gallons)+' gallon')}}
else if(id==='car-payment'){b=input('p','车价 ($)',30000)+input('d','首付 ($)',5000)+input('r','年利率 (%)',6.5)+input('n','贷款期限（月）',60,'number','1')+button;fn=()=>{let price=num('p',0),down=num('d',0),rate=num('r',0,100),n=num('n',1,120);if(price===null||down===null||rate===null||n===null||down>price)return bad('请检查车价、首付、利率和贷款期限');let principal=price-down,r=rate/1200,m=r?principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):principal/n;$('out').innerHTML=result('$'+fmt(m),'预计月供 · 贷款本金 $'+fmt(principal)+' · 总还款约 $'+fmt(m*n))};n='未包含销售税、牌照、Dealer fee、保险等实际购车成本。'}
else if(id==='mortgage'){b=input('p','房价 ($)',500000)+input('d','首付 ($)',100000)+input('r','年利率 (%)',6.5)+input('n','贷款年限',30,'number','1')+button;fn=()=>{let price=num('p',0),down=num('d',0),rate=num('r',0,100),years=num('n',1,50);if(price===null||down===null||rate===null||years===null||down>price)return bad('请检查房价、首付、利率和贷款年限');let principal=price-down,r=rate/1200,n=years*12,m=r?principal*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):principal/n;$('out').innerHTML=result('$'+fmt(m),'每月本金+利息 · 贷款本金 $'+fmt(principal)+' · 预计总还款 $'+fmt(m*n))};n='这里只计算本金和利息（P&I），未包含房产税、房屋保险、HOA 等费用。'}
else if(id==='china-us-time'){b=select('z','美国时区',['纽约 Eastern Time','芝加哥 Central Time','丹佛 Mountain Time','洛杉矶 Pacific Time'])+input('t','美国当地时间','','datetime-local')+button;fn=()=>{let v=$('t').value;if(!v)return bad('请选择美国当地日期和时间');let d=new Date(v),off={'纽约 Eastern Time':-4,'芝加哥 Central Time':-5,'丹佛 Mountain Time':-6,'洛杉矶 Pacific Time':-7}[$('z').value],cn=new Date(d.getTime()-off*3600000+8*3600000);$('out').innerHTML=result(cn.toISOString().slice(0,16).replace('T',' '),'中国北京时间（按当前夏令时规则近似）')}};n='美国冬夏令时会改变时差；当前版本按夏令时常见偏移快速计算。'}
else if(id==='age'){b=input('b','出生日期','','date')+button;fn=()=>{let v=$('b').value;if(!v)return bad('请选择出生日期');let bdate=new Date(v+'T00:00:00'),now=new Date();if(bdate>now)return bad('出生日期不能晚于今天');let a=now.getFullYear()-bdate.getFullYear();if(now.getMonth()<bdate.getMonth()||(now.getMonth()===bdate.getMonth()&&now.getDate()<bdate.getDate()))a--;$('out').innerHTML=result(a+' 岁','当前年龄')}}
else if(id==='date-diff'){b=input('a','开始日期','','date')+input('b','结束日期','','date')+button;fn=()=>{if(!$('a').value||!$('b').value)return bad('请选择开始和结束日期');let a=new Date($('a').value+'T00:00:00'),b=new Date($('b').value+'T00:00:00');$('out').innerHTML=result(fmt(Math.round(Math.abs(b-a)/86400000))+' 天','两个日期相差')}}
else if(id==='shoe-size'){b=select('d','换算方向',['中国男鞋码 → US 男鞋','US 男鞋 → 中国码','中国女鞋码 → US 女鞋','US 女鞋 → 中国女鞋'])+input('v','鞋码',42)+button;fn=()=>{let v=num('v',1,100);if(v===null)return bad('请输入有效鞋码');let d=$('d').value;let r=d==='中国男鞋码 → US 男鞋'?v-33.5:d==='US 男鞋 → 中国码'?v+33.5:d==='中国女鞋码 → US 女鞋'?v-33.5:v+33.5;$('out').innerHTML=result(fmt(r),'参考鞋码（按中国/欧码近似换算）')}};n='鞋码不是完全统一标准。美国男鞋/女鞋、品牌和鞋型都会有差异，购买前请以品牌尺码表为准。'}
else if(id==='mattress'){b=select('d','床垫尺寸',['Twin','Twin XL','Full / Double','Queen','King','California King'])+`<div id="out" class="result"><div class="big">38 × 75 in</div><div class="label">约 96.5 × 190.5 cm</div></div>`;fn=()=>{const x={Twin:['38 × 75 in','约 96.5 × 190.5 cm'],'Twin XL':['38 × 80 in','约 96.5 × 203.2 cm'],'Full / Double':['54 × 75 in','约 137.2 × 190.5 cm'],Queen:['60 × 80 in','约 152.4 × 203.2 cm'],King:['76 × 80 in','约 193 × 203.2 cm'],'California King':['72 × 84 in','约 182.9 × 213.4 cm']}[$('d').value];$('out').querySelector('.big').textContent=x[0];$('out').querySelector('.label').textContent=x[1]}}
else if(id==='psi'){b=input('v','压力',35)+select('d','换算方向',['PSI → Bar','Bar → PSI'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='PSI → Bar'?v*.0689475729:v/.0689475729;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
else if(id==='hp-kw'){b=input('v','功率',100)+select('d','换算方向',['HP → kW','kW → HP'])+button;fn=()=>{let v=num('v',0);if(v===null)return bad();let d=$('d').value,r=d==='HP → kW'?v*.745699872:v/.745699872;$('out').innerHTML=result(fmt(r),d.split(' → ')[1])}}
return {html:shell(t,b,n),fn};}
function renderTool(){const m=location.pathname.match(/\/tools\/([^/]+)\.html$/);if(!m)return;const id=m[1];const x=calculator(id);if(!x)return;document.title=`${tools.find(t=>t.id===id).name} - ToolKu`;let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.appendChild(meta)}meta.content=`${tools.find(t=>t.id===id).name}：${tools.find(t=>t.id===id).desc}。ToolKu 美国华人生活工具箱，免费在线使用。`;document.body.innerHTML=x.html;const btn=$('calc-btn');if(btn)btn.addEventListener('click',x.fn)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{renderHome();renderTool()});else{renderHome();renderTool()}