const tools=[
{id:'tip-calculator',cat:'钱 & 工资',icon:'💵',name:'小费计算器',desc:'餐厅、外卖、理发等快速计算小费',popular:1},{id:'salary-calculator',cat:'钱 & 工资',icon:'💰',name:'税前工资估算',desc:'年薪、月薪、周薪快速换算',popular:1},{id:'hourly-to-salary',cat:'钱 & 工资',icon:'🧮',name:'时薪转年薪',desc:'输入时薪和工作时间估算年收入',popular:1},{id:'split-bill',cat:'钱 & 工资',icon:'🧾',name:'AA 分账计算器',desc:'多人吃饭快速平均分账',popular:1},{id:'sales-tax',cat:'钱 & 工资',icon:'🏷️',name:'Sales Tax 计算器',desc:'商品价格加销售税计算最终付款',popular:1},{id:'discount',cat:'购物',icon:'🛍️',name:'折扣计算器',desc:'计算打折后的价格和省下多少钱',popular:1},{id:'currency',cat:'钱 & 工资',icon:'💱',name:'美元人民币换算',desc:'美元与人民币快速换算',popular:1},{id:'temp',cat:'单位换算',icon:'🌡️',name:'华氏度 ↔ 摄氏度',desc:'美国天气和生活温度快速换算',popular:1},{id:'weight',cat:'单位换算',icon:'⚖️',name:'磅 ↔ 公斤',desc:'lb、kg、oz 日常重量换算',popular:1},{id:'length',cat:'单位换算',icon:'📏',name:'英寸 ↔ 厘米',desc:'inch、cm、feet 快速换算'},{id:'distance',cat:'单位换算',icon:'🚗',name:'英里 ↔ 公里',desc:'Miles 与 KM 快速换算',popular:1},{id:'area',cat:'单位换算',icon:'🏠',name:'平方英尺 ↔ 平方米',desc:'美国房屋面积快速换算',popular:1},{id:'volume',cat:'单位换算',icon:'🥛',name:'加仑 ↔ 升',desc:'Gallon、Liter、Quart 换算'},{id:'mpg',cat:'汽车',icon:'⛽',name:'MPG ↔ L/100km',desc:'美国汽车油耗换算',popular:1},{id:'gas-cost',cat:'汽车',icon:'⛽',name:'加油成本计算器',desc:'估算一次开车需要多少油钱'},{id:'car-payment',cat:'汽车',icon:'🚙',name:'汽车月供计算器',desc:'根据车价、利率和期限计算月供',popular:1},{id:'mortgage',cat:'房屋',icon:'🏡',name:'房贷月供计算器',desc:'估算本金、利息和每月付款',popular:1},{id:'china-us-time',cat:'时间日期',icon:'🕐',name:'中美时间转换',desc:'美国时间与中国时间快速转换',popular:1},{id:'age',cat:'时间日期',icon:'🎂',name:'年龄计算器',desc:'输入生日计算准确年龄'},{id:'date-diff',cat:'时间日期',icon:'📅',name:'日期差计算器',desc:'计算两个日期相差多少天'},{id:'shoe-size',cat:'尺码',icon:'👟',name:'中美鞋码转换',desc:'中国、US、EU 鞋码参考'},{id:'mattress',cat:'尺码',icon:'🛏️',name:'美国床垫尺寸',desc:'Twin、Full、Queen、King 尺寸查询'},{id:'psi',cat:'汽车 / 技术',icon:'🔧',name:'PSI ↔ Bar',desc:'轮胎气压和工业压力换算'},{id:'hp-kw',cat:'汽车 / 技术',icon:'⚡',name:'HP ↔ kW',desc:'马力与千瓦快速换算'}];
const $=id=>document.getElementById(id),fmt=n=>Number(n).toLocaleString('en-US',{maximumFractionDigits:2});
function card(t,mini=false){return `<a class="${mini?'mini-card':'tool-card'}" href="tools/${t.id}.html"><span class="tool-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.desc}</p></a>`}
function renderHome(){const p=$('popular-grid'),c=$('category-list');if(!p||!c)return;p.innerHTML=tools.filter(t=>t.popular).slice(0,12).map(t=>card(t)).join('');const cats={};tools.forEach(t=>(cats[t.cat]??=[]).push(t));c.innerHTML=Object.entries(cats).map(([cat,arr])=>`<div class="category"><h3>${cat}</h3><div class="category-grid">${arr.map(t=>card(t,true)).join('')}</div></div>`).join('');$('tool-search')?.addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();document.querySelectorAll('#popular-grid .tool-card,#category-list .mini-card').forEach(el=>el.style.display=!q||el.textContent.toLowerCase().includes(q)?'block':'none')})}
function input(id,label,value='',type='number',step='any'){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${value}" step="${step}"></div>`}function result(v,l){return `<div class="result"><div class="big">${v}</div><div class="label">${l}</div></div>`}
function shell(t,body,note=''){return `<header class="site-header"><a class="brand" href="/"><span class="brand-mark">T</span>ToolKu</a><nav><a href="/">首页</a><a href="/#categories">全部工具</a><a href="https://openaa.com" target="_blank" rel="noopener">OpenAA</a></nav></header><main class="tool-shell"><section class="tool-page"><h1>${t.icon} ${t.name}</h1><p class="subtitle">${t.desc}</p>${body}${note?`<div class="note">${note}</div>`:''}<div class="tool-nav"><a href="/">← 返回 ToolKu</a><a href="tools/${t.id}.html">重新计算</a></div></section></main><footer>ToolKu.com · 美国华人生活工具箱<br><small>计算结果仅供参考。</small></footer>`}
function calculator(id){const t=tools.find(x=>x.id===id)||tools[0];let b='',s='',n='';
if(id==='tip-calculator'){b=input('bill','账单金额 ($)')+`<div class="field"><label>小费比例</label><select id="tip"><option value=".15">15%</option><option value=".18">18%</option><option value=".20" selected>20%</option><option value=".25">25%</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let b=+$('bill').value||0,p=+$('tip').value,t=b*p;$('out').innerHTML=result('$'+fmt(t),'小费金额 · 含小费总额 $'+fmt(b+t))}`}
else if(id==='salary-calculator'){b=input('a','年薪 ($)')+`<div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let a=+$('a').value||0;$('out').innerHTML=result('$'+fmt(a/12),'估算月薪 · 税前')}`}
else if(id==='hourly-to-salary'){b=input('h','时薪 ($)',20)+input('w','每周工作小时',40)+input('y','每年工作周数',52)+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let h=+$('h').value||0,w=+$('w').value||0,y=+$('y').value||52;$('out').innerHTML=result('$'+fmt(h*w*y),'估算年薪（税前）')}`}
else if(id==='split-bill'){b=input('b','总账单 ($)')+input('p','人数',2,'number','1')+input('t','小费比例 (%)',20)+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let b=+$('b').value||0,p=Math.max(1,+$('p').value||1),t=(+$('t').value||0)/100,total=b*(1+t);$('out').innerHTML=result('$'+fmt(total/p),'每人应付 · 总计 $'+fmt(total))}`}
else if(id==='sales-tax'){b=input('p','商品价格 ($)')+input('t','销售税率 (%)',8.875)+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let p=+$('p').value||0,t=(+$('t').value||0)/100;$('out').innerHTML=result('$'+fmt(p*(1+t)),'最终价格 · 税额 $'+fmt(p*t))}`}
else if(id==='discount'){b=input('p','原价 ($)')+input('o','折扣 (%)',20)+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let p=+$('p').value||0,o=(+$('o').value||0)/100;$('out').innerHTML=result('$'+fmt(p*(1-o)),'折后价格 · 节省 $'+fmt(p*o))}`}
else if(id==='currency'){b=input('a','金额',100)+`<div class="field"><label>方向</label><select id="d"><option>USD → CNY</option><option>CNY → USD</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let a=+$('a').value||0,r=$('d').value==='USD → CNY'?a*7.2:a/7.2;$('out').innerHTML=result(($('d').value==='USD → CNY'?'¥':'$')+fmt(r),'示例参考汇率：1 USD ≈ 7.20 CNY')}`;n='正式使用时请以银行或实时汇率服务为准。'}
else if(id==='temp'){b=input('v','温度',32)+`<div class="field"><label>方向</label><select id="d"><option>°F → °C</option><option>°C → °F</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='°F → °C'?(v-32)*5/9:v*9/5+32;$('out').innerHTML=result(fmt(r)+'°','换算结果')}`}
else if(id==='weight'){b=input('v','重量',1)+`<div class="field"><label>方向</label><select id="d"><option>lb → kg</option><option>kg → lb</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='lb → kg'?v*.45359237:v/.45359237;$('out').innerHTML=result(fmt(r),$('d').value.split(' → ')[1])}`}
else if(id==='length'){b=input('v','长度',1)+`<div class="field"><label>方向</label><select id="d"><option>inch → cm</option><option>cm → inch</option><option>feet → meter</option><option>meter → feet</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,d=$('d').value,r=d==='inch → cm'?v*2.54:d==='cm → inch'?v/2.54:d==='feet → meter'?v*.3048:v/.3048;$('out').innerHTML=result(fmt(r),'换算结果')}`}
else if(id==='distance'){b=input('v','距离',1)+`<div class="field"><label>方向</label><select id="d"><option>Miles → KM</option><option>KM → Miles</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='Miles → KM'?v*1.609344:v/1.609344;$('out').innerHTML=result(fmt(r),'换算结果')}`}
else if(id==='area'){b=input('v','面积',1000)+`<div class="field"><label>方向</label><select id="d"><option>sq ft → ㎡</option><option>㎡ → sq ft</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='sq ft → ㎡'?v*.092903:v/.092903;$('out').innerHTML=result(fmt(r),'换算结果')}`}
else if(id==='volume'){b=input('v','容量',1)+`<div class="field"><label>方向</label><select id="d"><option>Gallon → Liter</option><option>Liter → Gallon</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='Gallon → Liter'?v*3.785411784:v/3.785411784;$('out').innerHTML=result(fmt(r),'换算结果')}`}
else if(id==='mpg'){b=input('v','MPG',25)+`<div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||1;$('out').innerHTML=result(fmt(235.214583/v)+' L/100km','约等于')}`}
else if(id==='gas-cost'){b=input('m','行驶里程 (miles)',100)+input('g','车辆 MPG',25)+input('p','汽油价格 ($/gallon)',3.5)+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let m=+$('m').value||0,g=+$('g').value||1,p=+$('p').value||0;$('out').innerHTML=result('$'+fmt(m/g*p),'预计油费')}`}
else if(id==='car-payment'||id==='mortgage'){let car=id==='car-payment';b=input('p',car?'车价 ($)':'房价 ($)',car?30000:500000)+input('d','首付 ($)',car?5000:100000)+input('r','年利率 (%)',6.5)+input('n',car?'贷款月数':'贷款年限',car?60:30,'number','1')+`<div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let p=Math.max(0,(+$('p').value||0)-($('d').value||0)),r=(+$('r').value||0)/1200,n=${car?'(+$(\'n\').value||60)':'(+$(\'n\').value||30)*12'},m=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;$('out').innerHTML=result('$'+fmt(m),'预计月供 · 不含其他费用')}`;n=car?'汽车实际成本还可能包含税费、注册费、保险等。':'房贷月供未包含地税、房屋保险、HOA 等。'}
else if(id==='china-us-time'){b=`<div class="field"><label>美国时间</label><input id="dt" type="datetime-local"></div><div class="field"><label>美国时区</label><select id="z"><option value="-4">纽约 Eastern 夏令时</option><option value="-5">纽约 Eastern 标准时</option><option value="-7">洛杉矶 Pacific 夏令时</option><option value="-8">洛杉矶 Pacific 标准时</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">转换</button></div><div id="out"></div>`;s=`function calc(){let d=new Date($('dt').value);if(isNaN(d))d=new Date();let u=d.getTime()-(+$('z').value)*3600000,c=new Date(u+8*3600000);$('out').innerHTML=result(c.toLocaleString('zh-CN',{hour12:false}),'中国时间 UTC+8')}`;n='美国实行夏令时；纽约与中国通常相差 12 或 13 小时。'}
else if(id==='age'){b=`<div class="field"><label>出生日期</label><input id="d" type="date"></div><div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let b=new Date($('d').value),n=new Date(),y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth();if(n.getDate()<b.getDate())m--;if(m<0){y--;m+=12}$('out').innerHTML=result(y+' 岁 '+m+' 个月','当前年龄')}`}
else if(id==='date-diff'){b=`<div class="row"><div class="field"><label>开始日期</label><input id="a" type="date"></div><div class="field"><label>结束日期</label><input id="b" type="date"></div></div><div class="buttons"><button class="btn primary" onclick="calc()">计算</button></div><div id="out"></div>`;s=`function calc(){let a=new Date($('a').value),b=new Date($('b').value),d=Math.round(Math.abs(b-a)/86400000);$('out').innerHTML=result(d+' 天','两个日期相差')}`}
else if(id==='shoe-size'){b=input('v','中国鞋码',42)+`<div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let c=+$('v').value||0;$('out').innerHTML=result('US 男 '+fmt(c-33.5)+' · 女 '+fmt(c-34.5),'常见近似换算；不同品牌可能不同')}`}
else if(id==='mattress'){b=`<div class="field"><label>选择尺寸</label><select id="s"><option>Twin</option><option>Full / Double</option><option>Queen</option><option>King</option><option>California King</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">查看</button></div><div id="out"></div>`;s=`function calc(){let d={Twin:'38 × 75 in','Full / Double':'54 × 75 in',Queen:'60 × 80 in',King:'76 × 80 in','California King':'72 × 84 in'};$('out').innerHTML=result(d[$('s').value],$('s').value+' 标准尺寸')}`}
else if(id==='psi'){b=input('v','压力',35)+`<div class="field"><label>方向</label><select id="d"><option>PSI → Bar</option><option>Bar → PSI</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='PSI → Bar'?v*.0689475729:v/.0689475729;$('out').innerHTML=result(fmt(r),'换算结果')}`}
else if(id==='hp-kw'){b=input('v','数值',100)+`<div class="field"><label>方向</label><select id="d"><option>HP → kW</option><option>kW → HP</option></select></div><div class="buttons"><button class="btn primary" onclick="calc()">换算</button></div><div id="out"></div>`;s=`function calc(){let v=+$('v').value||0,r=$('d').value==='HP → kW'?v*.745699872:v/.745699872;$('out').innerHTML=result(fmt(r),'换算结果')}`}
document.body.innerHTML=shell(t,b,n)+`<script>${s}<\/script>`;document.title='ToolKu '+t.name+'｜美国华人生活工具'}
renderHome();const path=location.pathname.split('/').pop().replace('.html','');if(location.pathname.includes('/tools/'))calculator(path);